### ISSUE TITLE
Share buttons and Open Graph images

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/fixmyblock-wordpress#52]
Neha mentioned that there are no share buttons on the site so we should probably stick these on, especially on the case study pages! and also ensure there are the open graph images to go with them.

**Comment by zarino** [comment]
There are now share buttons in the sidebar of all pages.

I also tracked down a misconfiguration that was causing the homepage (fixmyblock.org) to have a small, square image when shared on social media, rather than the nice wide social sharing image. (Somehow, the "featured image" for the homepage had got set to the favicon file, so the Open Graph plugin was using that.)
