### ISSUE TITLE
Delayed user survey

### ISSUE THREAD

**Issue by ajparsons** [mysociety/fixmyblock-wordpress#69]
To replace the current surveys, I’d like to use a delayed email to survey users and find out after the fact if the website was useful. 
This involves either a link to the mailchimp sign-up (http://eepurl.com/hAfHRP) or integrating the mailchimp sign-up into the page ([gist](https://gist.github.com/ajparsons/ddf67ee4770986ab9f54b37cb7cc2f2a)). 

I would also like something on the page to pass the current url on as a parameter to the form submit or the link to the mailchimp sign-up (there’s a dummy version of this in the gist above). This might be in the body of the page, or in the pop-up if we want to keep that.

What are people’s thoughts on the preferred way to do this?

@MyfanwyNixon : This was my rough text to explain the email box if you want to make changes:

>We'd like to send you an email in a few weeks to find out if your has issue improved and how FixMyBlock can be more helpful. If you enter your email below, we will send you one message in a few weeks.

**Comment by ajparsons** [comment]
I've got the actual survey draft up, if you could have a look at that @JenMysoc? https://survey.alchemer.com/s3/6373631/FixMyBlock-Survey-2021

**Comment by MyfanwyNixon** [comment]
Cheers, how about:

>We'd like to follow up in a few weeks' time, to see whether there's been any progress on your issue, and to get your thoughts on how we can make FixMyBlock more helpful. If that sounds good, please enter your email address below.

**Comment by zarino** [comment]
Has the pre-exit popup survey been particularly well used so far? If not, then I’d be wary of relying on another similar popup to gather people’s email addresses.

A while back we were considering some sort of "I have this problem too!" call-out box in the middle / end of advice pages – where people could provide their email address to:

* Be notified when there are updates on this type of issue
* Potentially be put in touch with other people facing the same issue, once there are enough of them
* Potentially be led through an automated Mailchimp campaign, with a series of suggestions and prompts delivered every few weeks.

The idea of automated Mailchimp stuff sort of ran out of steam, and I think this whole feature got abandoned along with it. But I could imagine something that offered at least some of the things above, plus the thing you’re interested in:

* Get a follow-up email in a few weeks, asking how your issue is going

My instinct is that integrating it into the actual content of the page (rather than being hidden in a sidebar or footer or popup) plus making it clear that they’ll get some personal benefit out of it, are the keys to getting any significant number of signups.

Another advantage of having it embedded in the page for each problem type, is that we can pre-record what type of issue the person is experiencing, so might not need to ask that question in the survey. Just a thought!

Anyway, avoiding the temptation to balloon this ticket into something bigger than it is, perhaps we just launch the signup boxes with some generic wording like Myf’s above, and then use it as a starting off point for TBUK to consider other ways they could add value to the "subscription"? Thoughts @MyfanwyNixon ?

**Comment by ajparsons** [comment]
I'd say there hasn't been huge benefit to the pop-up and integrating in page is better. 

I was intending for their to be a hidden path of variables recording the original page, so technically that first question shouldn't be necessary, but I was wondering about people with multiple problems and so it seemed ok if not too long. 

On the final point, this could eventually grow a 'also sign up to mail list' tick box like the mysociety ones that could put them in a seperate segment? So I don't think technically a huge way off this if TBUK wanted to go down that line.

**Comment by MyfanwyNixon** [comment]
Yeah I like the idea of getting rid of the pop-up. And Zarino yes your idea does sound sensible. Let's add it to the next meeting's agenda.

**Comment by ajparsons** [comment]
The mailchimp delay has successfully worked for my campaign, so I think that bit of it is ready. Should I be trying to integrate it with the site or should I leave that to you @zarino?

**Comment by zarino** [comment]
@ajparsons feel free to have a go yourself, if you’re able!

**Comment by ajparsons** [comment]
This is live.
